---
title: "datasets merging"
format: html
---

## Creation illiterate rate 

```{r}
young_pop <- young_pop |> mutate("Value"= Value * 10^3, "Indicator"= "Population aged 15-24 years (number)")
illiterate_rate <- inner_join(illiteracy, young_pop, by = c("Country", "Time")) 
illiterate_rate <- illiterate_rate |> rename("Illiterate"="Value.x", "YoungPop"="Value.y")
illiterate_rate <- illiterate_rate |> mutate("illiterate_rate"= (Illiterate/YoungPop)*100) |> filter(!is.na(illiterate_rate))

## Creation de groupe
illiterate_rate <- illiterate_rate |> group_by(Time) |> 
  mutate(GROUP = case_when(
      illiterate_rate <= quantile(illiterate_rate, 0.3, na.rm = TRUE) ~ 1,
      quantile(illiterate_rate, 0.3, na.rm = TRUE) < illiterate_rate & illiterate_rate <= quantile(illiterate_rate, 0.70, na.rm = TRUE) ~ 2,
      quantile(illiterate_rate, 0.70, na.rm = TRUE) < illiterate_rate ~ 3,
      TRUE ~ NA ))
```


## Creation expenditure rate 
```{r}
GDP <- GDP |> mutate("Value"= Value / 10^6, "Indicator"= "GDP, US$ (millions)")

expenditure_rate <- inner_join(educ_expenditure, GDP, by = c("Country", "Time")) 
expenditure_rate <- expenditure_rate |> mutate("exp_rate"= Value.x/Value.y) 
```


```{r}
data_inter <- inner_join(illiterate_rate, expenditure_rate, by = c("Country", "Time"))
data_inter <- inner_join(data_inter, young_pop, by = c("Country", "Time"))
```

```{r}
illiteracy_enrol <- inner_join(illiterate_rate, enrolment, by=c("Country", "Time"))
```

